# Generated by Django 4.0.2 on 2022-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflapp', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='highlights',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
