# Generated by Django 4.0.2 on 2022-04-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nflapp', '0004_alter_link_highlights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='day',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home',
            new_name='gameid',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='loser',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='week_year',
        ),
        migrations.RemoveField(
            model_name='game',
            name='PtsL',
        ),
        migrations.RemoveField(
            model_name='game',
            name='PtsW',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOL',
        ),
        migrations.RemoveField(
            model_name='game',
            name='TOW',
        ),
        migrations.RemoveField(
            model_name='game',
            name='YdsL',
        ),
        migrations.RemoveField(
            model_name='game',
            name='YdsW',
        ),
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='week',
        ),
    ]
