# Generated by Django 4.0.2 on 2022-04-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nflapp', '0005_rename_day_game_away_team_rename_home_game_gameid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
